# Generated by Django 4.2.9 on 2024-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='produc_image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
