# Generated by Django 4.2.9 on 2024-01-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produc_image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True),
        ),
    ]
