# Generated by Django 4.2.9 on 2024-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_produc_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Closed', 'Closed')], default='Pending', max_length=9, null=True),
        ),
    ]
